import RankwidthDomination.WitnessPipelineBounds
import RankwidthDomination.WitnessEncoding

/-! Uniform finite-machine witnesses tied to the actual graph-problem bytes. -/
set_option maxHeartbeats 2000000
set_option maxRecDepth 10000
set_option synthInstance.maxSize 100000
namespace RankwidthDomination.WitnessMachine
open WidthParameters WitnessDimensions WitnessEncoding DecompositionAlgorithm

theorem paperLabeling_length (k m : ℕ) :
    (paperLabeling k m).vertices.length = vertexCount k m := by
  change (constructionOrderRaw k m).length = vertexCount k m
  rw [RawPaperOrder.constructionOrderRaw_length,vertexCount_eq_card]

/-- Exact GraphProblem identity-order witness, generated by a single finite
machine from k,m with polynomial cost in the actual graph vertex count. -/
theorem orderGeneratorMachine_outputs_certificate (k m : ℕ) :
    orderGeneratorMachine.outputsInTime (dimensionInput k m)
      (GraphProblem.certificateBits (paperLabeling k m) .suppliedOrder (paperLabeling k m))
      (20000*(Fintype.card (Vertex k m)+1)^6) := by
  have h := orderGeneratorMachine_outputs_polynomial k m
  rw [← paperLabeling_length k m,orderCertificate_eq] at h
  exact h

theorem treeOutputWord_eq (k m : ℕ) (hk : 0 < k) :
    treeOutputWord k m = GraphProblem.treeBits (paperLabeling k m) (build k m) :=
  b1TreeWords_eq_treeBits hk

/-- The generated bytes are the complete tree shape and vertex labels of the
proved B.1 decomposition, not a claimed width or an external witness oracle. -/
theorem treeMachine_outputs_certificate {k m : ℕ} (φ : CNF k m) (hk : 0 < k) :
    treeMachine.outputsInTime (dimensionInput k m)
      (GraphProblem.certificateBits (paperLabeling k m) .suppliedDecomposition (decomposition φ hk))
      (20000*(Fintype.card (Vertex k m)+1)^6) := by
  have h := treeMachine_outputs_polynomial k m hk
  have he : treeCertificateWord (treeOutputWord k m) =
      GraphProblem.certificateBits (paperLabeling k m) .suppliedDecomposition (decomposition φ hk) := by
    change [true,false] ++ Padding.BinaryEncoding.wordCode (treeOutputWord k m) =
      [true,false] ++ Padding.BinaryEncoding.wordCode (GraphProblem.treeBits (paperLabeling k m) (build k m))
    rw [treeOutputWord_eq k m hk]
  rw [he] at h
  exact h

/-- Basic B.1 width and its actual uniform construction-time guarantee. -/
theorem uniform_basic_decomposition {k m : ℕ} (φ : CNF k m) (hk : 0 < k) :
    (decomposition φ hk).width (coreGraph φ false) ≤ 3*k+1 ∧
    treeMachine.outputsInTime (dimensionInput k m)
      (GraphProblem.certificateBits (paperLabeling k m) .suppliedDecomposition (decomposition φ hk))
      (20000*(Fintype.card (Vertex k m)+1)^6) :=
  ⟨decomposition_width_le φ hk,treeMachine_outputs_certificate φ hk⟩

/-- The exact 3k quantitative constant also has a uniform finite-machine witness. -/
theorem uniform_basic_decomposition_three_k {k m : ℕ} (φ : CNF k m) (hk : 2 ≤ k) :
    (decomposition φ (by omega)).width (coreGraph φ false) ≤ 3*k ∧
    treeMachine.outputsInTime (dimensionInput k m)
      (GraphProblem.certificateBits (paperLabeling k m) .suppliedDecomposition
        (decomposition φ (by omega))) (20000*(Fintype.card (Vertex k m)+1)^6) :=
  ⟨decomposition_width_le_three_k φ hk,treeMachine_outputs_certificate φ (by omega)⟩

/-- Completing choice vertices does not alter the computed certificate. -/
theorem uniform_split_decomposition {k m : ℕ} (φ : CNF k m) (hk : 0 < k) :
    (decomposition φ hk).width (coreGraph φ true) ≤ 3*k+2 ∧
    treeMachine.outputsInTime (dimensionInput k m)
      (GraphProblem.certificateBits (paperLabeling k m) .suppliedDecomposition (decomposition φ hk))
      (20000*(Fintype.card (Vertex k m)+1)^6) :=
  ⟨decomposition_split_width_le φ hk,treeMachine_outputs_certificate φ hk⟩

end RankwidthDomination.WitnessMachine
